### ISSUE TITLE
Initial documentation on promitor.io

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#37]
Initial documentation on promitor.io

### Specification

- [ ] Why this project? (#8)
- [ ] Provide documentation on how to run the image (#15)
- [ ] Provide documentation on configuration #35)
- [ ] Remove wiki for business features
