### ISSUE TITLE
Rename promitor-scraper to promitor-agent-scraper

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#393]
As of today our scraper is called [tomkerkhove/promitor-scraper](https://hub.docker.com/r/tomkerkhove/promitor-scraper) but with #347 we might add more types of agents.

## Task List
- [x] Rename our scraper and push Docker images to [tomkerkhove/promitor-agent-scraper](https://cloud.docker.com/repository/docker/tomkerkhove/promitor-agent-scraper)
- [x] Update all documentation
- [x] Update release automation
- [x] Update all old image (references) to point to new image

**Comment by tomkerkhove** [comment]
All docs is now pointing to new image name with preview release
