### ISSUE TITLE
Flexible Resource Discovery for scraping

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#512]
Our aim is to provide a configuration-as-code approach where all metrics that are scraped are in the configuration file.

This makes it very straight-forward what metrics are available and what resources we are scraping.

However, in some scenarios this is not scalable and we should use some sort of flexible resource determination which need to be scraped.

## Scenario
We have a big application which runs hundreds of nodes, ie. VMs, and need to have a unified way of operating them.

## Proposal
We could use an approach where we support people to configure a resource type with resource filter which is using [Azure resource Tags](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags).

This should feel very intuitive given this is a similar approach to how Kubernetes maps resources with each other

### Limitations 
- Limited to one resource group
- Limited to one resource type

## Caveats/Questions
- What would the outcome of this scraping be?
  - n metrics with a base metric which is defined in the configuration and suffixed with something? If so, what suffix?
  - One metric with aggregate of all?
  - One metric with [a metric label](https://prometheus.io/docs/practices/naming/#labels) per resource? _(Big perf impact)_
- Should we restrict the amount of resources in one tag combination? If so, how many?

## Open work

- [x] Provide a resource discovery agent
- [x] Provide support for configuring resource collection to scrape all discovered Azure resources
- [x] Provide support for scraping metrics for all discovered Azure resources
- [x] Provide unit tests for query builder (Moved to #1166)
- [x] Provide integration tests for discovery endpoint to ensure deserialization still works (Moved to #1167)
- [x] Provide updated version of guide to introduce new scrapers
- [x] Provide entry in changelog.promitor.io (Moved to #1176)

**Comment by tomkerkhove** [comment]
@mabsimms feel free to elaborate if you have other insights/concerns/ideas

**Comment by tomkerkhove** [comment]
Good news friends, we're commiting to this feature!

**Comment by tomkerkhove** [comment]
We've had a look at this and came up with the following idea.

Our current scraper will allow you to define how you'd if you want to use a static metric declaration or resource discovery in the `runtime.yml`. If we can, we'll even make it easier so that you can just mix and match them in the metric declaration.

When using resource discovery, you'll have to run a new container we will introduce which is in charge of, well, discovering the resources you'd like to scrape.

It would:
- Provide same runtime capabilities such as health endpoint, telemetry, way of configuring it
- Allow you to define a grouping of Azure resources (`resource group` / `resource collection` / suggestions?) with a friendly name which you'll be able to scrape. Resources that belong to the grouping will be done by using following filters:
    - Resource type (ie `Microsoft.LogicApps`)
    - Azure tag(s) (optional)
    - Azure Resource Group(s) (optional)
    - Subscription(s) (optional)

Our current scraper will interpret metrics declaration where you'll have the option to explicitly mention the resources to scrape or refer to a "resource collection".

If it's referring to a resource collection, it will ask the resource discovery container to get a list of resources for a given collection and scrape all of those and report it in the metric.

![resource-discovery](https://user-images.githubusercontent.com/4345663/76909712-49338c00-68ac-11ea-9492-7aa7bca8212f.png)

Any feedback on this approach is welcome!

**Comment by tomkerkhove** [comment]
Discovery will be done via Graph, throttling docs are up at https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview#throttling
