### ISSUE TITLE
Document what services we are using

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#95]
Document what services we are using and are so generous to provide this offering for free:

These should all be on README & promitor.io, except for GitHub Apps which should only end up in README.

### Used 3rd parties
**Services**:
- [ ]  **Travis CI** for building PRs #6
- [ ]  **Snyk.io** for vulnerability scanning (currently only docs because of [#143](https://github.com/snyk/snyk/issues/143)) #91 
- [ ]  **Renovate** for maintaining dependencies #70

**GitHub Apps**:
- [ ] **WIP** for blocking WIP PRs
- [ ] **Reminders** for setting reminders
- [ ] **Request Info** for requesting information for PRs without info
- [ ] **Stale** for managing issues
